server:
    port: 8081

spring:
    application:
        name: content-service
    jpa:
        hibernate:
            ddl-auto: update
    datasource: 
        url: jdbc:mysql://localhost:3306/content_details
        username: root
        password: 
        hikari: 
            minIdle: 10
            idle-timeout: 10000
            maximumPoolSize: 30
          
eureka: 
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://localhost:8661/eureka
        instance:
            hostname: localhost
            